name: noob_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.4.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Playball
      fonts:
        - asset: assets/fonts/Playball-q6o1.ttf
    - family: Moonhouse
      fonts:
        - asset: assets/fonts/moonhouse.ttf
    - family: plz
      fonts:
        - asset: assets/fonts/plz.ttf
    - family: SocialIcons
      fonts:
        - asset: assets/icons/SocialIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 400

  uses-material-design: true
  assets:
    - assets/images/GSsoc-Type-Logo-Black.png
    - assets/images/michael-dam-mEZ3PoFGs_k-unsplash.jpg
    - assets/images/back.png
